version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-serverless
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run verify
  test_serverless:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-serveless-{{ checksum "package.json" }}
            - v1-dependencies-serverless
      - run: npm install --prefix functions
      - save_cache:
          paths:
            - functions/node_modules
          key: v1-dependencies-serverless-{{ checksum "package.json" }}
      - run: npm run lint --prefix functions
  deploy:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm install --prefix functions
      - run: npm run build
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --force

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - test_serverless
      - deploy:
          requires:
            - test
            - test_serverless
          filters:
            branches:
              only: master
