version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.12.0
    working_directory: ~/repo

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: npm install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: sudo npm install -g codecov
    - run: npm run verify
    - run: npm test
    #    - run: npm run coverage
  deploy:
    docker:
    - image: circleci/node:8.12.0
    working_directory: ~/repo
    steps:
    - checkout
    - run: npm install
    - run: npm install --prefix functions
    - run: npm run build
    - run:
        name: Deploy Master to Firebase
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --force
     - run:
        name: Deploy Cloud Functions to Firebase
        command: ./node_modules/.bin/firebase deploy --only functions --token=$FIREBASE_DEPLOY_TOKEN --force

workflows:
  version: 2

  -deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master
